"""Remove unwanted relationship between Tenant model and Invitation

Revision ID: 825e20afcb8c
Revises: c2b8f26d7f02
Create Date: 2026-04-09 22:04:19.694269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825e20afcb8c'
down_revision: Union[str, Sequence[str], None] = 'c2b8f26d7f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
