"""Create Plan Table

Revision ID: 9a0a6a5adb66
Revises: 1dbd0f723b67
Create Date: 2026-04-15 09:00:26.159251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0a6a5adb66'
down_revision: Union[str, Sequence[str], None] = '1dbd0f723b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tenants', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'owner_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
