"""Create Relation Between Plan & Tenant Tables

Revision ID: c5a224361d2d
Revises: 9a0a6a5adb66
Create Date: 2026-04-15 09:01:01.452286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a224361d2d'
down_revision: Union[str, Sequence[str], None] = '9a0a6a5adb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tenants', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'plan_id')
    # ### end Alembic commands ###
